CREATE TABLE capsules
id UUID PRIMARY KEY
owner_id UUID NOT NULL
title VARCHAR(255) NOT NULL
message TEXT NOT NULL
status VARCHAR(30) NOT NULL
visibility VARCHAR(30) NOT NULL
open_at TIMESTAMP NOT NULL
created_at TIMESTAMP NOT NULL
updated_at TIMESTAMP NOT NULL
